//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdeCamp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id_co { get; set; }
        public int cod_co { get; set; }
        public string text_co { get; set; }
        public System.DateTime date_co { get; set; }
        public int id_post_co { get; set; }
    
        public virtual student student { get; set; }
        public virtual post post { get; set; }
    }
}
