//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdeCamp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class like_po
    {
        public int id_like { get; set; }
        public int cod_stud { get; set; }
        public int type_like { get; set; }
        public int id_po { get; set; }
        public System.DateTime date_post { get; set; }
    
        public virtual student student { get; set; }
        public virtual post post { get; set; }
        public virtual type_like type_like1 { get; set; }
    }
}
