//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdeCamp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class udecampEntities : DbContext
    {
        public udecampEntities()
            : base("name=udecampEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<career> career { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<like_po> like_po { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<type_like> type_like { get; set; }
        public virtual DbSet<type_post> type_post { get; set; }
    }
}
